/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppArchiveRouteImport } from './routes/_app.archive'
import { Route as AppArchiveAnalyticsRouteImport } from './routes/_app.archive-analytics'
import { Route as AppArchiveManagerRouteImport } from './routes/_app.archive-manager'
import { Route as AppCalendarRouteImport } from './routes/_app.calendar'
import { Route as AppCertificatesRouteImport } from './routes/_app.certificates'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppLifecycleRouteImport } from './routes/_app.lifecycle'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppRegistrationsRouteImport } from './routes/_app.registrations'
import { Route as AppSavedRouteImport } from './routes/_app.saved'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppAdminApprovalsRouteImport } from './routes/_app.admin.approvals'
import { Route as AppAdminArchiveLogsRouteImport } from './routes/_app.admin.archive-logs'
import { Route as AppAdminAuditRouteImport } from './routes/_app.admin.audit'
import { Route as AppAdminCommandCenterRouteImport } from './routes/_app.admin.command-center'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin.dashboard'
import { Route as AppAdminDepartmentsRouteImport } from './routes/_app.admin.departments'
import { Route as AppAdminDigitalTwinRouteImport } from './routes/_app.admin.digital-twin'
import { Route as AppAdminPredictiveIntelligenceRouteImport } from './routes/_app.admin.predictive-intelligence'
import { Route as AppAdminReportsRouteImport } from './routes/_app.admin.reports'
import { Route as AppAdminSettingsRouteImport } from './routes/_app.admin.settings'
import { Route as AppAdminUsersRouteImport } from './routes/_app.admin.users'
import { Route as AppEventsIndexRouteImport } from './routes/_app.events.index'
import { Route as AppEventsEventIdRouteImport } from './routes/_app.events.$eventId'
import { Route as AppOrganizerIndexRouteImport } from './routes/_app.organizer.index'
import { Route as AppOrganizerAnalyticsRouteImport } from './routes/_app.organizer.analytics'
import { Route as AppOrganizerAttendanceRouteImport } from './routes/_app.organizer.attendance'
import { Route as AppOrganizerCreateRouteImport } from './routes/_app.organizer.create'
import { Route as AppOrganizerDashboardRouteImport } from './routes/_app.organizer.dashboard'
import { Route as AppOrganizerEventsRouteImport } from './routes/_app.organizer.events'
import { Route as AppOrganizerRegistrationsRouteImport } from './routes/_app.organizer.registrations'
import { Route as AppStudentDashboardRouteImport } from './routes/_app.student.dashboard'
import { Route as AppSummaryEventIdRouteImport } from './routes/_app.summary.$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppArchiveRoute = AppArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveAnalyticsRoute = AppArchiveAnalyticsRouteImport.update({
  id: '/archive-analytics',
  path: '/archive-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppArchiveManagerRoute = AppArchiveManagerRouteImport.update({
  id: '/archive-manager',
  path: '/archive-manager',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppCertificatesRoute = AppCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppLifecycleRoute = AppLifecycleRouteImport.update({
  id: '/lifecycle',
  path: '/lifecycle',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppRegistrationsRoute = AppRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovalsRoute = AppAdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminArchiveLogsRoute = AppAdminArchiveLogsRouteImport.update({
  id: '/admin/archive-logs',
  path: '/admin/archive-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminCommandCenterRoute = AppAdminCommandCenterRouteImport.update({
  id: '/admin/command-center',
  path: '/admin/command-center',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDepartmentsRoute = AppAdminDepartmentsRouteImport.update({
  id: '/admin/departments',
  path: '/admin/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDigitalTwinRoute = AppAdminDigitalTwinRouteImport.update({
  id: '/admin/digital-twin',
  path: '/admin/digital-twin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminPredictiveIntelligenceRoute =
  AppAdminPredictiveIntelligenceRouteImport.update({
    id: '/admin/predictive-intelligence',
    path: '/admin/predictive-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminReportsRoute = AppAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsEventIdRoute = AppEventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerIndexRoute = AppOrganizerIndexRouteImport.update({
  id: '/organizer/',
  path: '/organizer/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerAnalyticsRoute = AppOrganizerAnalyticsRouteImport.update({
  id: '/organizer/analytics',
  path: '/organizer/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerAttendanceRoute = AppOrganizerAttendanceRouteImport.update({
  id: '/organizer/attendance',
  path: '/organizer/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerCreateRoute = AppOrganizerCreateRouteImport.update({
  id: '/organizer/create',
  path: '/organizer/create',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerDashboardRoute = AppOrganizerDashboardRouteImport.update({
  id: '/organizer/dashboard',
  path: '/organizer/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerEventsRoute = AppOrganizerEventsRouteImport.update({
  id: '/organizer/events',
  path: '/organizer/events',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizerRegistrationsRoute =
  AppOrganizerRegistrationsRouteImport.update({
    id: '/organizer/registrations',
    path: '/organizer/registrations',
    getParentRoute: () => AppRoute,
  } as any)
const AppStudentDashboardRoute = AppStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSummaryEventIdRoute = AppSummaryEventIdRouteImport.update({
  id: '/summary/$eventId',
  path: '/summary/$eventId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/archive': typeof AppArchiveRoute
  '/archive-analytics': typeof AppArchiveAnalyticsRoute
  '/archive-manager': typeof AppArchiveManagerRoute
  '/calendar': typeof AppCalendarRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/lifecycle': typeof AppLifecycleRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/registrations': typeof AppRegistrationsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/archive-logs': typeof AppAdminArchiveLogsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/command-center': typeof AppAdminCommandCenterRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/digital-twin': typeof AppAdminDigitalTwinRoute
  '/admin/predictive-intelligence': typeof AppAdminPredictiveIntelligenceRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/organizer/analytics': typeof AppOrganizerAnalyticsRoute
  '/organizer/attendance': typeof AppOrganizerAttendanceRoute
  '/organizer/create': typeof AppOrganizerCreateRoute
  '/organizer/dashboard': typeof AppOrganizerDashboardRoute
  '/organizer/events': typeof AppOrganizerEventsRoute
  '/organizer/registrations': typeof AppOrganizerRegistrationsRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/summary/$eventId': typeof AppSummaryEventIdRoute
  '/admin/': typeof AppAdminIndexRoute
  '/events/': typeof AppEventsIndexRoute
  '/organizer/': typeof AppOrganizerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/archive': typeof AppArchiveRoute
  '/archive-analytics': typeof AppArchiveAnalyticsRoute
  '/archive-manager': typeof AppArchiveManagerRoute
  '/calendar': typeof AppCalendarRoute
  '/certificates': typeof AppCertificatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/lifecycle': typeof AppLifecycleRoute
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/registrations': typeof AppRegistrationsRoute
  '/saved': typeof AppSavedRoute
  '/settings': typeof AppSettingsRoute
  '/admin/approvals': typeof AppAdminApprovalsRoute
  '/admin/archive-logs': typeof AppAdminArchiveLogsRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/command-center': typeof AppAdminCommandCenterRoute
  '/admin/dashboard': typeof AppAdminDashboardRoute
  '/admin/departments': typeof AppAdminDepartmentsRoute
  '/admin/digital-twin': typeof AppAdminDigitalTwinRoute
  '/admin/predictive-intelligence': typeof AppAdminPredictiveIntelligenceRoute
  '/admin/reports': typeof AppAdminReportsRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/events/$eventId': typeof AppEventsEventIdRoute
  '/organizer/analytics': typeof AppOrganizerAnalyticsRoute
  '/organizer/attendance': typeof AppOrganizerAttendanceRoute
  '/organizer/create': typeof AppOrganizerCreateRoute
  '/organizer/dashboard': typeof AppOrganizerDashboardRoute
  '/organizer/events': typeof AppOrganizerEventsRoute
  '/organizer/registrations': typeof AppOrganizerRegistrationsRoute
  '/student/dashboard': typeof AppStudentDashboardRoute
  '/summary/$eventId': typeof AppSummaryEventIdRoute
  '/admin': typeof AppAdminIndexRoute
  '/events': typeof AppEventsIndexRoute
  '/organizer': typeof AppOrganizerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/archive': typeof AppArchiveRoute
  '/_app/archive-analytics': typeof AppArchiveAnalyticsRoute
  '/_app/archive-manager': typeof AppArchiveManagerRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/certificates': typeof AppCertificatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/lifecycle': typeof AppLifecycleRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/registrations': typeof AppRegistrationsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/admin/approvals': typeof AppAdminApprovalsRoute
  '/_app/admin/archive-logs': typeof AppAdminArchiveLogsRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/command-center': typeof AppAdminCommandCenterRoute
  '/_app/admin/dashboard': typeof AppAdminDashboardRoute
  '/_app/admin/departments': typeof AppAdminDepartmentsRoute
  '/_app/admin/digital-twin': typeof AppAdminDigitalTwinRoute
  '/_app/admin/predictive-intelligence': typeof AppAdminPredictiveIntelligenceRoute
  '/_app/admin/reports': typeof AppAdminReportsRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/events/$eventId': typeof AppEventsEventIdRoute
  '/_app/organizer/analytics': typeof AppOrganizerAnalyticsRoute
  '/_app/organizer/attendance': typeof AppOrganizerAttendanceRoute
  '/_app/organizer/create': typeof AppOrganizerCreateRoute
  '/_app/organizer/dashboard': typeof AppOrganizerDashboardRoute
  '/_app/organizer/events': typeof AppOrganizerEventsRoute
  '/_app/organizer/registrations': typeof AppOrganizerRegistrationsRoute
  '/_app/student/dashboard': typeof AppStudentDashboardRoute
  '/_app/summary/$eventId': typeof AppSummaryEventIdRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/events/': typeof AppEventsIndexRoute
  '/_app/organizer/': typeof AppOrganizerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/archive'
    | '/archive-analytics'
    | '/archive-manager'
    | '/calendar'
    | '/certificates'
    | '/dashboard'
    | '/lifecycle'
    | '/notifications'
    | '/profile'
    | '/registrations'
    | '/saved'
    | '/settings'
    | '/admin/approvals'
    | '/admin/archive-logs'
    | '/admin/audit'
    | '/admin/command-center'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/digital-twin'
    | '/admin/predictive-intelligence'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/events/$eventId'
    | '/organizer/analytics'
    | '/organizer/attendance'
    | '/organizer/create'
    | '/organizer/dashboard'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/student/dashboard'
    | '/summary/$eventId'
    | '/admin/'
    | '/events/'
    | '/organizer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/archive'
    | '/archive-analytics'
    | '/archive-manager'
    | '/calendar'
    | '/certificates'
    | '/dashboard'
    | '/lifecycle'
    | '/notifications'
    | '/profile'
    | '/registrations'
    | '/saved'
    | '/settings'
    | '/admin/approvals'
    | '/admin/archive-logs'
    | '/admin/audit'
    | '/admin/command-center'
    | '/admin/dashboard'
    | '/admin/departments'
    | '/admin/digital-twin'
    | '/admin/predictive-intelligence'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/events/$eventId'
    | '/organizer/analytics'
    | '/organizer/attendance'
    | '/organizer/create'
    | '/organizer/dashboard'
    | '/organizer/events'
    | '/organizer/registrations'
    | '/student/dashboard'
    | '/summary/$eventId'
    | '/admin'
    | '/events'
    | '/organizer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/archive'
    | '/_app/archive-analytics'
    | '/_app/archive-manager'
    | '/_app/calendar'
    | '/_app/certificates'
    | '/_app/dashboard'
    | '/_app/lifecycle'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/registrations'
    | '/_app/saved'
    | '/_app/settings'
    | '/_app/admin/approvals'
    | '/_app/admin/archive-logs'
    | '/_app/admin/audit'
    | '/_app/admin/command-center'
    | '/_app/admin/dashboard'
    | '/_app/admin/departments'
    | '/_app/admin/digital-twin'
    | '/_app/admin/predictive-intelligence'
    | '/_app/admin/reports'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/events/$eventId'
    | '/_app/organizer/analytics'
    | '/_app/organizer/attendance'
    | '/_app/organizer/create'
    | '/_app/organizer/dashboard'
    | '/_app/organizer/events'
    | '/_app/organizer/registrations'
    | '/_app/student/dashboard'
    | '/_app/summary/$eventId'
    | '/_app/admin/'
    | '/_app/events/'
    | '/_app/organizer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/archive': {
      id: '/_app/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof AppArchiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive-analytics': {
      id: '/_app/archive-analytics'
      path: '/archive-analytics'
      fullPath: '/archive-analytics'
      preLoaderRoute: typeof AppArchiveAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/archive-manager': {
      id: '/_app/archive-manager'
      path: '/archive-manager'
      fullPath: '/archive-manager'
      preLoaderRoute: typeof AppArchiveManagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/certificates': {
      id: '/_app/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AppCertificatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lifecycle': {
      id: '/_app/lifecycle'
      path: '/lifecycle'
      fullPath: '/lifecycle'
      preLoaderRoute: typeof AppLifecycleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/registrations': {
      id: '/_app/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof AppRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approvals': {
      id: '/_app/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AppAdminApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/archive-logs': {
      id: '/_app/admin/archive-logs'
      path: '/admin/archive-logs'
      fullPath: '/admin/archive-logs'
      preLoaderRoute: typeof AppAdminArchiveLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/command-center': {
      id: '/_app/admin/command-center'
      path: '/admin/command-center'
      fullPath: '/admin/command-center'
      preLoaderRoute: typeof AppAdminCommandCenterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/dashboard': {
      id: '/_app/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/departments': {
      id: '/_app/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AppAdminDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/digital-twin': {
      id: '/_app/admin/digital-twin'
      path: '/admin/digital-twin'
      fullPath: '/admin/digital-twin'
      preLoaderRoute: typeof AppAdminDigitalTwinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/predictive-intelligence': {
      id: '/_app/admin/predictive-intelligence'
      path: '/admin/predictive-intelligence'
      fullPath: '/admin/predictive-intelligence'
      preLoaderRoute: typeof AppAdminPredictiveIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/reports': {
      id: '/_app/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AppAdminReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/': {
      id: '/_app/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/events/$eventId': {
      id: '/_app/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof AppEventsEventIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/': {
      id: '/_app/organizer/'
      path: '/organizer'
      fullPath: '/organizer/'
      preLoaderRoute: typeof AppOrganizerIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/analytics': {
      id: '/_app/organizer/analytics'
      path: '/organizer/analytics'
      fullPath: '/organizer/analytics'
      preLoaderRoute: typeof AppOrganizerAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/attendance': {
      id: '/_app/organizer/attendance'
      path: '/organizer/attendance'
      fullPath: '/organizer/attendance'
      preLoaderRoute: typeof AppOrganizerAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/create': {
      id: '/_app/organizer/create'
      path: '/organizer/create'
      fullPath: '/organizer/create'
      preLoaderRoute: typeof AppOrganizerCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/dashboard': {
      id: '/_app/organizer/dashboard'
      path: '/organizer/dashboard'
      fullPath: '/organizer/dashboard'
      preLoaderRoute: typeof AppOrganizerDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/events': {
      id: '/_app/organizer/events'
      path: '/organizer/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof AppOrganizerEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizer/registrations': {
      id: '/_app/organizer/registrations'
      path: '/organizer/registrations'
      fullPath: '/organizer/registrations'
      preLoaderRoute: typeof AppOrganizerRegistrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student/dashboard': {
      id: '/_app/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AppStudentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/summary/$eventId': {
      id: '/_app/summary/$eventId'
      path: '/summary/$eventId'
      fullPath: '/summary/$eventId'
      preLoaderRoute: typeof AppSummaryEventIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppArchiveRoute: typeof AppArchiveRoute
  AppArchiveAnalyticsRoute: typeof AppArchiveAnalyticsRoute
  AppArchiveManagerRoute: typeof AppArchiveManagerRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCertificatesRoute: typeof AppCertificatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLifecycleRoute: typeof AppLifecycleRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegistrationsRoute: typeof AppRegistrationsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppAdminApprovalsRoute: typeof AppAdminApprovalsRoute
  AppAdminArchiveLogsRoute: typeof AppAdminArchiveLogsRoute
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCommandCenterRoute: typeof AppAdminCommandCenterRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminDepartmentsRoute: typeof AppAdminDepartmentsRoute
  AppAdminDigitalTwinRoute: typeof AppAdminDigitalTwinRoute
  AppAdminPredictiveIntelligenceRoute: typeof AppAdminPredictiveIntelligenceRoute
  AppAdminReportsRoute: typeof AppAdminReportsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppEventsEventIdRoute: typeof AppEventsEventIdRoute
  AppOrganizerAnalyticsRoute: typeof AppOrganizerAnalyticsRoute
  AppOrganizerAttendanceRoute: typeof AppOrganizerAttendanceRoute
  AppOrganizerCreateRoute: typeof AppOrganizerCreateRoute
  AppOrganizerDashboardRoute: typeof AppOrganizerDashboardRoute
  AppOrganizerEventsRoute: typeof AppOrganizerEventsRoute
  AppOrganizerRegistrationsRoute: typeof AppOrganizerRegistrationsRoute
  AppStudentDashboardRoute: typeof AppStudentDashboardRoute
  AppSummaryEventIdRoute: typeof AppSummaryEventIdRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppOrganizerIndexRoute: typeof AppOrganizerIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppArchiveRoute: AppArchiveRoute,
  AppArchiveAnalyticsRoute: AppArchiveAnalyticsRoute,
  AppArchiveManagerRoute: AppArchiveManagerRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCertificatesRoute: AppCertificatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLifecycleRoute: AppLifecycleRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegistrationsRoute: AppRegistrationsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppAdminApprovalsRoute: AppAdminApprovalsRoute,
  AppAdminArchiveLogsRoute: AppAdminArchiveLogsRoute,
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCommandCenterRoute: AppAdminCommandCenterRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminDepartmentsRoute: AppAdminDepartmentsRoute,
  AppAdminDigitalTwinRoute: AppAdminDigitalTwinRoute,
  AppAdminPredictiveIntelligenceRoute: AppAdminPredictiveIntelligenceRoute,
  AppAdminReportsRoute: AppAdminReportsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppEventsEventIdRoute: AppEventsEventIdRoute,
  AppOrganizerAnalyticsRoute: AppOrganizerAnalyticsRoute,
  AppOrganizerAttendanceRoute: AppOrganizerAttendanceRoute,
  AppOrganizerCreateRoute: AppOrganizerCreateRoute,
  AppOrganizerDashboardRoute: AppOrganizerDashboardRoute,
  AppOrganizerEventsRoute: AppOrganizerEventsRoute,
  AppOrganizerRegistrationsRoute: AppOrganizerRegistrationsRoute,
  AppStudentDashboardRoute: AppStudentDashboardRoute,
  AppSummaryEventIdRoute: AppSummaryEventIdRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppOrganizerIndexRoute: AppOrganizerIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
